# Autoware State Monitor: Planning Simulator Parameters
/**:
  ros__parameters:
    # modules_names: string array
    module_names: [
      "map",
      "sensing",
      "perception",
      "localization",
      "planning",
      "control",
      "vehicle",
      "system"
    ]

    # Topic Config
    ## item_count: int
    ## configs: top level
    ### itemN: second level
    #### name: string
    #### module: string
    #### timeout[s]: double (0: none)
    #### warn_rate[hz]: double (0: none)
    #### type: string
    #### transient_local: bool
    topic_configs:
      item_count: 11
      configs:
        item0:
          name: "/map/vector_map"
          module: "map"
          timeout: 0.0
          warn_rate: 0.0
          type: "autoware_lanelet2_msgs/msg/MapBin"
          transient_local: True

        item1:
          name: "/map/pointcloud_map"
          module: "map"
          timeout: 0.0
          warn_rate: 0.0
          type: "sensor_msgs/msg/PointCloud2"
          transient_local: True

        item2:
          name: "/perception/object_recognition/objects"
          module: "perception"
          timeout: 1.0
          warn_rate: 5.0
          type: "autoware_perception_msgs/msg/DynamicObjectArray"

        item3:
          name: "/initialpose"
          module: "localization"
          timeout: 0.0
          warn_rate: 0.0
          type: "geometry_msgs/msg/PoseWithCovarianceStamped"

        item4:
          name: "/planning/mission_planning/route"
          module: "planning"
          timeout: 0.0
          warn_rate: 0.0
          type: "autoware_planning_msgs/msg/Route"
          transient_local: True

        item5:
          name: "/planning/scenario_planning/trajectory"
          module: "planning"
          timeout: 1.0
          warn_rate: 5.0
          type: "autoware_planning_msgs/msg/Trajectory"

        item6:
          name: "/control/trajectory_follower/control_cmd"
          module: "control"
          timeout: 1.0
          warn_rate: 5.0
          type: "autoware_control_msgs/msg/ControlCommandStamped"

        item7:
          name: "/control/vehicle_cmd"
          module: "control"
          timeout: 1.0
          warn_rate: 5.0
          type: "autoware_vehicle_msgs/msg/VehicleCommand"

        item8:
          name: "/vehicle/status/twist"
          module: "vehicle"
          timeout: 1.0
          warn_rate: 5.0
          type: "geometry_msgs/msg/TwistStamped"

        item9:
          name: "/vehicle/status/steering"
          module: "vehicle"
          timeout: 1.0
          warn_rate: 5.0
          type: "autoware_vehicle_msgs/msg/Steering"

        item10:
          name: "/system/emergency/control_cmd"
          module: "system"
          timeout: 1.0
          warn_rate: 5.0
          type: "autoware_control_msgs/msg/ControlCommandStamped"

    # Param Config
    ## item_count: int
    ## configs: top level
    ### itemN: second level
    #### name: string
    #### module: string
    # param_configs:
    #   item_count: 1
    #   configs:
    #     item0:
    #       name: "/vehicle_info"
    #       module: "vehicle"

    # TF Config
    ## item_count: int
    ## configs: top level
    ### itemN: second level
    #### module: string
    #### from: string
    #### to: string
    #### timeout[s]: double (0: none)
    tf_configs:
      item_count: 1
      configs:
        item0:
          module: "localization"
          from: "map"
          to: "base_link"
          timeout: 1.0
